In [2]:
print('hi')

hi


In [4]:
import numpy as np


b.Создайте массив из 10 нулей

In [5]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c. Создать массив из 10 единиц

In [6]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d. Создать массив из 10 пятерок

In [7]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e. Создать массив из целых чисел от 10 до 50

In [8]:
array=np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f. Создать массив из четных чисел от 10 до 50

In [9]:
array=np.arange(10,51,2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g.Создать матрицу 3х3 с числами от 0 до 8

In [15]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h.Создать единичную матрицу 3x3

In [20]:
array=np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


i.Используйте NumPy для генерации случайного числа от 0 до 1

In [27]:
array=np.random.randint(0,1)
print(array)

0


j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [28]:
array=np.random.randn(25)
print(array)

[ 0.85732101 -0.18860825 -0.48183767 -0.1383687   0.75585846  0.4288342
 -0.96013437  0.7055287  -0.69910942  0.55666312  1.60120797 -0.57465974
 -0.87927147  0.64832026 -0.79454438  0.34342572 -0.87555898 -1.2221882
 -2.16538389  0.19313778 -0.37003085  0.65352377 -0.1384783  -0.08060037
 -1.44954936]


k.Создайте следующую матрицу используя функции библиотеки NumPy:

In [67]:
array=np.linspace(0.01,1,100).reshape(10,10)
print(array)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах# это наша стартовая матрицаmat = np.arange(1,26).reshape(5,5)print(mat)


In [79]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицуиз стартовой:

In [85]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l.

In [93]:
print(mat[3,4])

20


n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [99]:
print(mat[0:3,1])

[ 2  7 12]


o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [94]:
print(mat[4,:])

[21 22 23 24 25]


p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [97]:
print(mat[3:,:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


q.Получить сумму всех значений в стартовой матрице mat

In [105]:
print(mat.sum())

325


r. Получить стандартное отклонение в стартовой матрице mat

In [104]:
print(mat.std())

7.211102550927978


s.Получить сумму значений в колонках в стартовой матрице mat

In [106]:
print(sum(mat))

[55 60 65 70 75]
